// Shared measurement configuration for Laquatwin instruments
// This constant is the single source of truth for field validation ranges, labels, and units

export const MEASUREMENT_FIELDS = {
  ph: {
    key: 'ph',
    label: 'pH',
    unit: '',
    min: 0,
    max: 14,
    step: 0.01,
    meterGroup: 'pH Meter',
    laquatwin: 'pH-11/22/33',
    description: 'Acidity/alkalinity',
  },
  conductivity: {
    key: 'conductivity',
    label: 'Conductivity',
    unit: 'µS/cm',
    min: 0,
    max: 199900,
    step: 1,
    meterGroup: 'Conductivity Meter',
    laquatwin: 'EC-11/22/33',
    description: 'Electrical conductivity',
  },
  salinity: {
    key: 'salinity',
    label: 'Salinity',
    unit: '‰',
    min: 0,
    max: 100,
    step: 0.1,
    meterGroup: 'Salinity Meter',
    laquatwin: 'Salt-11/22',
    description: 'Practical salinity',
  },
  nitrate: {
    key: 'nitrate',
    label: 'Nitrate',
    unit: 'mg/L',
    min: 0,
    max: 6200,
    step: 0.1,
    meterGroup: 'Ion-Selective Electrodes (ISE)',
    laquatwin: 'NO3-11',
    description: 'Nitrate ion (NO₃⁻) concentration',
  },
  calcium: {
    key: 'calcium',
    label: 'Calcium',
    unit: 'mg/L',
    min: 0,
    max: 4000,
    step: 0.1,
    meterGroup: 'Ion-Selective Electrodes (ISE)',
    laquatwin: 'Ca-11',
    description: 'Calcium ion (Ca²⁺) concentration',
  },
  potassium: {
    key: 'potassium',
    label: 'Potassium',
    unit: 'mg/L',
    min: 0,
    max: 2000,
    step: 0.1,
    meterGroup: 'Ion-Selective Electrodes (ISE)',
    laquatwin: 'K-11',
    description: 'Potassium ion (K⁺) concentration',
  },
  sodium: {
    key: 'sodium',
    label: 'Sodium',
    unit: 'mg/L',
    min: 0,
    max: 2000,
    step: 0.1,
    meterGroup: 'Ion-Selective Electrodes (ISE)',
    laquatwin: 'Na-11',
    description: 'Sodium ion (Na⁺) concentration',
  },
  temperature: {
    key: 'temperature',
    label: 'Temperature',
    unit: '°C',
    min: -100,
    max: 100,
    step: 0.1,
    meterGroup: 'Common',
    laquatwin: 'All models',
    description: 'Water temperature',
  },
} as const;

export type MeasurementFieldKey = keyof typeof MEASUREMENT_FIELDS;

// Priority order for displaying measurements in card previews, popups, etc.
export const MEASUREMENT_PRIORITY = [
  'ph',
  'conductivity',
  'salinity',
  'nitrate',
  'calcium',
  'potassium',
  'sodium',
  'temperature',
] as const;